services:
  rnaseq:
    image: benson1231/bioc-rnaseq:v2
    container_name: rnaseq-pipeline
    working_dir: /workspace/workflow/
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    entrypoint: ["bash"]