# These paths act as defaults in config.yaml but can be overridden dynamically via CLI with --config.

# Directory containing raw FASTQ data.
raw_data_dir: "../.test/test_data"

# Root directory for analysis outputs.
output_dir: "results"

# Directory will contain transcriptome reference files download from this pipeline.
references_dir: "references"

# Path to the samplesheet (CSV file).
# - Must include the following columns: sample_number,sample_name,abbreviation_name,condition,color
# - The pipeline uses this file to determine which samples to process and the corresponding FASTQ file locations.
samplesheet: "../.test/config/samplesheet.csv"

# Path to the comparison file (CSV file).
# - Must include the following columns: Number,Treatment,Control
# - The pipeline will generate differential analysis results based on this configuration.
comparison: "../.test/config/comparison.csv"